import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import { Container, Main, SideBar, TopBar } from '@/layout';
import { Footer } from '@/layout/Footer';
import { ThemeProvider } from '@/context/ThemeContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Diego',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <ThemeProvider>
          <Container>
            <TopBar />
            <SideBar />
            <Main>{children}</Main>
            <Footer />
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
