import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Cosas',
  description: 'Generated by create next app',
};

export default function CosasLayout({
  children,
  cosa1,
  cosa2,
}: {
  children: React.ReactNode;
  cosa1: React.ReactNode;
  cosa2: React.ReactNode;
}) {
  return (
    <>
      {cosa1}
      <br />
      {cosa2}
      <br />
      {children}
    </>
  );
}
